<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="1" tests="4" name="com.qa.opencart.test.LoginpageTest" time="0.911" errors="0" timestamp="2024-05-17T23:16:38 IST" skipped="0">
  <testcase classname="com.qa.opencart.test.LoginpageTest" name="loginURLTest" time="0.016">
    <failure message=".....URL didn&#039;t match expected [https://naveenautomationlabs.com/opencart/index.php?route=account/login] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/account]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: .....URL didn't match expected [https://naveenautomationlabs.com/opencart/index.php?route=account/login] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/account]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.qa.opencart.test.LoginpageTest.loginURLTest(LoginpageTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- loginURLTest -->
  <testcase classname="com.qa.opencart.test.LoginpageTest" name="loginPageTitleTest" time="0.017"/>
  <testcase classname="com.qa.opencart.test.LoginpageTest" name="forgotpwdexistTest" time="0.066"/>
  <testcase classname="com.qa.opencart.test.LoginpageTest" name="loginTest" time="0.812"/>
</testsuite> <!-- com.qa.opencart.test.LoginpageTest -->
